POST http://localhost:8080/addMessage
Content-Type: application/json

{
    "senderid":"2016141223043",
    "userid":"222222",
    "title":"老师们请注意",
    "content":"请老师及时出题"
}

#### For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);